apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      serviceAccountName: default-sa
      containers:
        - image: sonnguyen97/udagram-reverseproxy:v5
          name: reverseproxy
          resources:
            requests:
              memory: "64Mi"
              cpu: "180m"
            limits:
              memory: "987Mi"
              cpu: "240m"
          ports:
            - containerPort: 8080
